%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------

# Camera calibration and distortion parameters (OpenCV)
Camera.fx: 930.166 # 938.935 930.166
Camera.fy: 930.166 # 938.935 930.166
Camera.cx: 480.0   # 480.0   473.782
Camera.cy: 270.0   # 270.0   146.812

Camera.k1: -0.147571  # -0.157547 -0.147571
Camera.k2: -0.0943432 # -0.0896036 -0.0943432
Camera.p1: 0.0
Camera.p2: 0.0

# Camera frames per second
Camera.fps: 25.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Config path for Python detectors
DetectorConfigPath: configs/config_freiburg_001.json
Objects.maskErrosion: 10

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 4000

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.1  # originally 0.6
Viewer.KeyFrameLineWidth: 2
Viewer.GraphLineWidth: 4
Viewer.PointSize: 2
Viewer.CameraSize: 0.15  # originally 0.7
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -10   # originally -10
Viewer.ViewpointZ: -0.1
Viewer.ViewpointF: 2000
